language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.088.0
    - d: dmd-2.087.1
    - d: dmd-2.086.1
    - d: ldc-1.17.0
    - d: ldc-1.16.0
    - d: ldc-1.15.0
  allow_failures:
    - d: dmd-nightly

install:
  - mkdir bin

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub test --build=release

after_success:
 - bash <(curl -s https://codecov.io/bash)
