language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.093.1
    - d: ldc-1.23.0
  allow_failures:
    - d: dmd-nightly

install:
  - mkdir bin

script:
  - dub test --build=unittest-cov --compiler=${DC}
  # - dub test --build=release

after_success:
 - bash <(curl -s https://codecov.io/bash)
