language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.080.0
    - d: dmd-2.079.1
    - d: dmd-2.078.1
    - d: ldc-1.9.0
    - d: ldc-1.8.0
    - d: ldc-1.7.0
  allow_failures:
    - d: dmd-nightly

install:
  - mkdir bin

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub test --build=release

after_success:
 - bash <(curl -s https://codecov.io/bash)
