language: dlang
install:
 - sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
 - sudo apt-get update
 - sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
 - sudo apt-get update
 - sudo apt-get -y install dmd-bin
 - git clone https://github.com/atilaneves/unit-threaded.git
 - git clone https://github.com/atilaneves/dtest.git
script: rdmd -Iunit-threaded dtest/dtest.d -u unit-threaded