language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.082.1
    - d: dmd-2.081.2
    - d: dmd-2.079.1
    - d: ldc-1.12.0
    - d: ldc-1.11.0
    - d: ldc-1.10.0
  allow_failures:
    - d: dmd-nightly

install:
  - mkdir bin

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub test --build=release

after_success:
 - bash <(curl -s https://codecov.io/bash)
