//Automatically generated by dtest, do not edit by hand
import unit_threaded.runner;
import std.stdio;

int main(string[] args) {
    writeln("\nAutomatically generated file ut.d");
    writeln(`Running unit tests from dirs ["tests"]`);
    return args.runTests!(
                          "tests.cerealiser_impl",
                          "tests.multidimensional_array",
                          "tests.reset",
                          "tests.nested",
                          "tests.enums",
                          "tests.decode",
                          "tests.static_array",
                          "tests.pointers",
                          "tests.encode",
                          "tests.encode_decode",
                          "tests.bugs",
                          "tests.structs",
                          "tests.classes",
                          "tests.range",
                          "tests.compile_time",
                          "tests.utils",
                          );
}
