name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
          - macos-14
        dc:
          - dmd-2.111.0
          - dmd-2.100.0
          - ldc-1.41.0
          - ldc-1.28.0

        exclude:
          - dc: dmd-2.100.0
            os: macos-14

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        run: dub test -q --build=unittest-cov

      - name: Build binary
        run: dub build -q

      - uses: codecov/codecov-action@v5.1.2
